#!/bin/sh

GROUPNAME=$(basename $0|perl -lane 'if($F[0] =~ /^aws_(\w+)_elb_http5xx_(.*)/) { print $1}')
LBNAME=$(basename $0|perl -lane 'if($F[0] =~ /^aws_(\w+)_elb_http5xx_(.*)/) { print $2}')
LBNAME_SHORT=$(echo $LBNAME|cut -c 1-8)

DIMENSIONS=LoadBalancerName=$LBNAME
NAMESPACE="AWS/ELB"
CATEGORY_NAME="${LBNAME_SHORT}/AWS/ELB"
METRICNAME=HTTPCode_Backend_5XX

if [ -z "$LBNAME" ]; then
    echo 'Cannot read lb name' >&2
    exit 1
fi

case $1 in
    config)
        echo "graph_title $LBNAME error 500"
        echo "graph_vlabel errors"
        echo "graph_category $CATEGORY_NAME"
        echo 'count.label count'
        exit 0;;
esac

if [ -z "$JAVA_HOME" ]; then
    JAVA_HOME=$(readlink -f $(which java)|grep -P -o '.*(?=/bin/java)')
fi

if [ -z "$AWS_ACCESS_KEY_ID" ]; then
    echo 'AWS ID not specified. Set env.AWS_ACCESS_KEY_ID' >&2
    exit 1
fi

if [ -z "$AWS_SECRET_ACCESS_KEY" ]; then
    echo 'AWS Secret not specified. Set env.AWS_SECRET_ACCESS_KEY' >&2
    exit 1
fi

if [ ! -x $AWS_CLOUDWATCH_HOME/bin/mon-get-stats ]; then
    echo 'Cannot execute mon-get-stats. Set env.AWS_CLOUDWATCH_HOME' >&2
    exit 1
fi

TMPFILE=$(mktemp)
if [ ! -w $TMPFILE ]; then
    echo "Cannot write to temp file $TMPFILE" >&2
    exit 1
fi

export AWS_CLOUDWATCH_HOME
export JAVA_HOME
$AWS_CLOUDWATCH_HOME/bin/mon-get-stats $METRICNAME --region $EC2_REGION -I $AWS_ACCESS_KEY_ID -S $AWS_SECRET_ACCESS_KEY -n $NAMESPACE --dimensions $DIMENSIONS -s Sum --period 300 --start-time $(date --iso-8601=seconds --date="5 minutes ago") > $TMPFILE

if [ $? -ne 0 ]; then
    echo 'Failed to run mon-get-stats' >&2
    rm $TMPFILE
    exit 1
fi

COUNT=$(cat $TMPFILE|awk '{print $3}'|grep -Po '[0-9]*\.[0-9]{0,2}')

# There is no response when the count is none
if [ -z $COUNT ]; then
    COUNT=0
fi

rm $TMPFILE

echo "count.value $COUNT"

exit 0
